plugins {
    id 'java-library'
    id "io.github.0ffz.github-packages" version "1.2.1" // Plugin for anonymous inclusion of artifacts hosted in github package registry
}

dependencies {
    api libs.jmeCore
    runtimeOnly libs.jmeJogg
    runtimeOnly libs.jmePlugins

    
    


    api libs.heart
    api libs.minie
    api libs.log4j.core
    api libs.log4j.api
    api libs.lemur
    api libs.lemur.proto
}

processResources {
    def versionPropsFile = file("${rootProject.projectDir}/version.properties")
    def versionProps = new Properties()
    versionProps.load(new FileInputStream(versionPropsFile))

    inputs.file versionPropsFile

    filesMatching("version.properties") {
        expand(
            version: versionProps['version'],
            buildDate: versionProps['buildDate']
        )
    }
}
